/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsFlyioRouteImport } from './routes/settings/flyio'
import { Route as SettingsApiKeysRouteImport } from './routes/settings/api-keys'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsFlyioRoute = SettingsFlyioRouteImport.update({
  id: '/settings/flyio',
  path: '/settings/flyio',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsApiKeysRoute = SettingsApiKeysRouteImport.update({
  id: '/settings/api-keys',
  path: '/settings/api-keys',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings/api-keys': typeof SettingsApiKeysRoute
  '/settings/flyio': typeof SettingsFlyioRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings/api-keys': typeof SettingsApiKeysRoute
  '/settings/flyio': typeof SettingsFlyioRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings/api-keys': typeof SettingsApiKeysRoute
  '/settings/flyio': typeof SettingsFlyioRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/settings/api-keys' | '/settings/flyio'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/settings/api-keys' | '/settings/flyio'
  id: '__root__' | '/' | '/settings/api-keys' | '/settings/flyio'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsApiKeysRoute: typeof SettingsApiKeysRoute
  SettingsFlyioRoute: typeof SettingsFlyioRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/flyio': {
      id: '/settings/flyio'
      path: '/settings/flyio'
      fullPath: '/settings/flyio'
      preLoaderRoute: typeof SettingsFlyioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/api-keys': {
      id: '/settings/api-keys'
      path: '/settings/api-keys'
      fullPath: '/settings/api-keys'
      preLoaderRoute: typeof SettingsApiKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsApiKeysRoute: SettingsApiKeysRoute,
  SettingsFlyioRoute: SettingsFlyioRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
