/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LogoExperimentRouteImport } from './routes/logo-experiment'
import { Route as GithubRouteImport } from './routes/github'
import { Route as GetStartedRouteImport } from './routes/get-started'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DnsRouteImport } from './routes/dns'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding/index'
import { Route as SettingsDnsRouteImport } from './routes/settings/dns'
import { Route as SettingsApiKeysRouteImport } from './routes/settings/api-keys'
import { Route as SettingsAccessRouteImport } from './routes/settings/access'
import { Route as ServicesServiceIdRouteImport } from './routes/services/$serviceId'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects/$projectId'
import { Route as OnboardingLayoutRouteImport } from './routes/onboarding/_layout'
import { Route as OauthConsentRouteImport } from './routes/oauth/consent'
import { Route as GithubappSuccessRouteImport } from './routes/githubapp/success'
import { Route as GithubappCallbackRouteImport } from './routes/githubapp/callback'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as OnboardingLayoutWelcomeRouteImport } from './routes/onboarding/_layout/welcome'
import { Route as OnboardingLayoutModeSelectRouteImport } from './routes/onboarding/_layout/mode-select'
import { Route as OnboardingLayoutGithubRepoRouteImport } from './routes/onboarding/_layout/github-repo'
import { Route as OnboardingLayoutGithubAppRouteImport } from './routes/onboarding/_layout/github-app'
import { Route as OnboardingLayoutCompleteRouteImport } from './routes/onboarding/_layout/complete'
import { Route as OnboardingLayoutAgentKeyRouteImport } from './routes/onboarding/_layout/agent-key'

const OnboardingRouteImport = createFileRoute('/onboarding')()

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoExperimentRoute = LogoExperimentRouteImport.update({
  id: '/logo-experiment',
  path: '/logo-experiment',
  getParentRoute: () => rootRouteImport,
} as any)
const GithubRoute = GithubRouteImport.update({
  id: '/github',
  path: '/github',
  getParentRoute: () => rootRouteImport,
} as any)
const GetStartedRoute = GetStartedRouteImport.update({
  id: '/get-started',
  path: '/get-started',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DnsRoute = DnsRouteImport.update({
  id: '/dns',
  path: '/dns',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OnboardingRoute,
} as any)
const SettingsDnsRoute = SettingsDnsRouteImport.update({
  id: '/settings/dns',
  path: '/settings/dns',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsApiKeysRoute = SettingsApiKeysRouteImport.update({
  id: '/settings/api-keys',
  path: '/settings/api-keys',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAccessRoute = SettingsAccessRouteImport.update({
  id: '/settings/access',
  path: '/settings/access',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesServiceIdRoute = ServicesServiceIdRouteImport.update({
  id: '/services/$serviceId',
  path: '/services/$serviceId',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/services/$serviceId.lazy').then((d) => d.Route),
)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/projects/$projectId.lazy').then((d) => d.Route),
)
const OnboardingLayoutRoute = OnboardingLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => OnboardingRoute,
} as any)
const OauthConsentRoute = OauthConsentRouteImport.update({
  id: '/oauth/consent',
  path: '/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const GithubappSuccessRoute = GithubappSuccessRouteImport.update({
  id: '/githubapp/success',
  path: '/githubapp/success',
  getParentRoute: () => rootRouteImport,
} as any)
const GithubappCallbackRoute = GithubappCallbackRouteImport.update({
  id: '/githubapp/callback',
  path: '/githubapp/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingLayoutWelcomeRoute = OnboardingLayoutWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => OnboardingLayoutRoute,
} as any)
const OnboardingLayoutModeSelectRoute =
  OnboardingLayoutModeSelectRouteImport.update({
    id: '/mode-select',
    path: '/mode-select',
    getParentRoute: () => OnboardingLayoutRoute,
  } as any)
const OnboardingLayoutGithubRepoRoute =
  OnboardingLayoutGithubRepoRouteImport.update({
    id: '/github-repo',
    path: '/github-repo',
    getParentRoute: () => OnboardingLayoutRoute,
  } as any)
const OnboardingLayoutGithubAppRoute =
  OnboardingLayoutGithubAppRouteImport.update({
    id: '/github-app',
    path: '/github-app',
    getParentRoute: () => OnboardingLayoutRoute,
  } as any)
const OnboardingLayoutCompleteRoute =
  OnboardingLayoutCompleteRouteImport.update({
    id: '/complete',
    path: '/complete',
    getParentRoute: () => OnboardingLayoutRoute,
  } as any)
const OnboardingLayoutAgentKeyRoute =
  OnboardingLayoutAgentKeyRouteImport.update({
    id: '/agent-key',
    path: '/agent-key',
    getParentRoute: () => OnboardingLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/dns': typeof DnsRoute
  '/docs': typeof DocsRoute
  '/features': typeof FeaturesRoute
  '/get-started': typeof GetStartedRoute
  '/github': typeof GithubRoute
  '/logo-experiment': typeof LogoExperimentRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/githubapp/callback': typeof GithubappCallbackRoute
  '/githubapp/success': typeof GithubappSuccessRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/onboarding': typeof OnboardingLayoutRouteWithChildren
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/services/$serviceId': typeof ServicesServiceIdRoute
  '/settings/access': typeof SettingsAccessRoute
  '/settings/api-keys': typeof SettingsApiKeysRoute
  '/settings/dns': typeof SettingsDnsRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/onboarding/agent-key': typeof OnboardingLayoutAgentKeyRoute
  '/onboarding/complete': typeof OnboardingLayoutCompleteRoute
  '/onboarding/github-app': typeof OnboardingLayoutGithubAppRoute
  '/onboarding/github-repo': typeof OnboardingLayoutGithubRepoRoute
  '/onboarding/mode-select': typeof OnboardingLayoutModeSelectRoute
  '/onboarding/welcome': typeof OnboardingLayoutWelcomeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/dns': typeof DnsRoute
  '/docs': typeof DocsRoute
  '/features': typeof FeaturesRoute
  '/get-started': typeof GetStartedRoute
  '/github': typeof GithubRoute
  '/logo-experiment': typeof LogoExperimentRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/githubapp/callback': typeof GithubappCallbackRoute
  '/githubapp/success': typeof GithubappSuccessRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/services/$serviceId': typeof ServicesServiceIdRoute
  '/settings/access': typeof SettingsAccessRoute
  '/settings/api-keys': typeof SettingsApiKeysRoute
  '/settings/dns': typeof SettingsDnsRoute
  '/projects': typeof ProjectsIndexRoute
  '/onboarding/agent-key': typeof OnboardingLayoutAgentKeyRoute
  '/onboarding/complete': typeof OnboardingLayoutCompleteRoute
  '/onboarding/github-app': typeof OnboardingLayoutGithubAppRoute
  '/onboarding/github-repo': typeof OnboardingLayoutGithubRepoRoute
  '/onboarding/mode-select': typeof OnboardingLayoutModeSelectRoute
  '/onboarding/welcome': typeof OnboardingLayoutWelcomeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/dns': typeof DnsRoute
  '/docs': typeof DocsRoute
  '/features': typeof FeaturesRoute
  '/get-started': typeof GetStartedRoute
  '/github': typeof GithubRoute
  '/logo-experiment': typeof LogoExperimentRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/githubapp/callback': typeof GithubappCallbackRoute
  '/githubapp/success': typeof GithubappSuccessRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/onboarding/_layout': typeof OnboardingLayoutRouteWithChildren
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/services/$serviceId': typeof ServicesServiceIdRoute
  '/settings/access': typeof SettingsAccessRoute
  '/settings/api-keys': typeof SettingsApiKeysRoute
  '/settings/dns': typeof SettingsDnsRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/onboarding/_layout/agent-key': typeof OnboardingLayoutAgentKeyRoute
  '/onboarding/_layout/complete': typeof OnboardingLayoutCompleteRoute
  '/onboarding/_layout/github-app': typeof OnboardingLayoutGithubAppRoute
  '/onboarding/_layout/github-repo': typeof OnboardingLayoutGithubRepoRoute
  '/onboarding/_layout/mode-select': typeof OnboardingLayoutModeSelectRoute
  '/onboarding/_layout/welcome': typeof OnboardingLayoutWelcomeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dns'
    | '/docs'
    | '/features'
    | '/get-started'
    | '/github'
    | '/logo-experiment'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/auth/callback'
    | '/githubapp/callback'
    | '/githubapp/success'
    | '/oauth/consent'
    | '/onboarding'
    | '/projects/$projectId'
    | '/services/$serviceId'
    | '/settings/access'
    | '/settings/api-keys'
    | '/settings/dns'
    | '/onboarding/'
    | '/projects'
    | '/onboarding/agent-key'
    | '/onboarding/complete'
    | '/onboarding/github-app'
    | '/onboarding/github-repo'
    | '/onboarding/mode-select'
    | '/onboarding/welcome'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/dns'
    | '/docs'
    | '/features'
    | '/get-started'
    | '/github'
    | '/logo-experiment'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/auth/callback'
    | '/githubapp/callback'
    | '/githubapp/success'
    | '/oauth/consent'
    | '/onboarding'
    | '/projects/$projectId'
    | '/services/$serviceId'
    | '/settings/access'
    | '/settings/api-keys'
    | '/settings/dns'
    | '/projects'
    | '/onboarding/agent-key'
    | '/onboarding/complete'
    | '/onboarding/github-app'
    | '/onboarding/github-repo'
    | '/onboarding/mode-select'
    | '/onboarding/welcome'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dns'
    | '/docs'
    | '/features'
    | '/get-started'
    | '/github'
    | '/logo-experiment'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/auth/callback'
    | '/githubapp/callback'
    | '/githubapp/success'
    | '/oauth/consent'
    | '/onboarding'
    | '/onboarding/_layout'
    | '/projects/$projectId'
    | '/services/$serviceId'
    | '/settings/access'
    | '/settings/api-keys'
    | '/settings/dns'
    | '/onboarding/'
    | '/projects/'
    | '/onboarding/_layout/agent-key'
    | '/onboarding/_layout/complete'
    | '/onboarding/_layout/github-app'
    | '/onboarding/_layout/github-repo'
    | '/onboarding/_layout/mode-select'
    | '/onboarding/_layout/welcome'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  DnsRoute: typeof DnsRoute
  DocsRoute: typeof DocsRoute
  FeaturesRoute: typeof FeaturesRoute
  GetStartedRoute: typeof GetStartedRoute
  GithubRoute: typeof GithubRoute
  LogoExperimentRoute: typeof LogoExperimentRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  GithubappCallbackRoute: typeof GithubappCallbackRoute
  GithubappSuccessRoute: typeof GithubappSuccessRoute
  OauthConsentRoute: typeof OauthConsentRoute
  OnboardingRoute: typeof OnboardingRouteWithChildren
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
  ServicesServiceIdRoute: typeof ServicesServiceIdRoute
  SettingsAccessRoute: typeof SettingsAccessRoute
  SettingsApiKeysRoute: typeof SettingsApiKeysRoute
  SettingsDnsRoute: typeof SettingsDnsRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logo-experiment': {
      id: '/logo-experiment'
      path: '/logo-experiment'
      fullPath: '/logo-experiment'
      preLoaderRoute: typeof LogoExperimentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/github': {
      id: '/github'
      path: '/github'
      fullPath: '/github'
      preLoaderRoute: typeof GithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-started': {
      id: '/get-started'
      path: '/get-started'
      fullPath: '/get-started'
      preLoaderRoute: typeof GetStartedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dns': {
      id: '/dns'
      path: '/dns'
      fullPath: '/dns'
      preLoaderRoute: typeof DnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/settings/dns': {
      id: '/settings/dns'
      path: '/settings/dns'
      fullPath: '/settings/dns'
      preLoaderRoute: typeof SettingsDnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/api-keys': {
      id: '/settings/api-keys'
      path: '/settings/api-keys'
      fullPath: '/settings/api-keys'
      preLoaderRoute: typeof SettingsApiKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/access': {
      id: '/settings/access'
      path: '/settings/access'
      fullPath: '/settings/access'
      preLoaderRoute: typeof SettingsAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$serviceId': {
      id: '/services/$serviceId'
      path: '/services/$serviceId'
      fullPath: '/services/$serviceId'
      preLoaderRoute: typeof ServicesServiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/_layout': {
      id: '/onboarding/_layout'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingLayoutRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/oauth/consent': {
      id: '/oauth/consent'
      path: '/oauth/consent'
      fullPath: '/oauth/consent'
      preLoaderRoute: typeof OauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/githubapp/success': {
      id: '/githubapp/success'
      path: '/githubapp/success'
      fullPath: '/githubapp/success'
      preLoaderRoute: typeof GithubappSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/githubapp/callback': {
      id: '/githubapp/callback'
      path: '/githubapp/callback'
      fullPath: '/githubapp/callback'
      preLoaderRoute: typeof GithubappCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/_layout/welcome': {
      id: '/onboarding/_layout/welcome'
      path: '/welcome'
      fullPath: '/onboarding/welcome'
      preLoaderRoute: typeof OnboardingLayoutWelcomeRouteImport
      parentRoute: typeof OnboardingLayoutRoute
    }
    '/onboarding/_layout/mode-select': {
      id: '/onboarding/_layout/mode-select'
      path: '/mode-select'
      fullPath: '/onboarding/mode-select'
      preLoaderRoute: typeof OnboardingLayoutModeSelectRouteImport
      parentRoute: typeof OnboardingLayoutRoute
    }
    '/onboarding/_layout/github-repo': {
      id: '/onboarding/_layout/github-repo'
      path: '/github-repo'
      fullPath: '/onboarding/github-repo'
      preLoaderRoute: typeof OnboardingLayoutGithubRepoRouteImport
      parentRoute: typeof OnboardingLayoutRoute
    }
    '/onboarding/_layout/github-app': {
      id: '/onboarding/_layout/github-app'
      path: '/github-app'
      fullPath: '/onboarding/github-app'
      preLoaderRoute: typeof OnboardingLayoutGithubAppRouteImport
      parentRoute: typeof OnboardingLayoutRoute
    }
    '/onboarding/_layout/complete': {
      id: '/onboarding/_layout/complete'
      path: '/complete'
      fullPath: '/onboarding/complete'
      preLoaderRoute: typeof OnboardingLayoutCompleteRouteImport
      parentRoute: typeof OnboardingLayoutRoute
    }
    '/onboarding/_layout/agent-key': {
      id: '/onboarding/_layout/agent-key'
      path: '/agent-key'
      fullPath: '/onboarding/agent-key'
      preLoaderRoute: typeof OnboardingLayoutAgentKeyRouteImport
      parentRoute: typeof OnboardingLayoutRoute
    }
  }
}

interface OnboardingLayoutRouteChildren {
  OnboardingLayoutAgentKeyRoute: typeof OnboardingLayoutAgentKeyRoute
  OnboardingLayoutCompleteRoute: typeof OnboardingLayoutCompleteRoute
  OnboardingLayoutGithubAppRoute: typeof OnboardingLayoutGithubAppRoute
  OnboardingLayoutGithubRepoRoute: typeof OnboardingLayoutGithubRepoRoute
  OnboardingLayoutModeSelectRoute: typeof OnboardingLayoutModeSelectRoute
  OnboardingLayoutWelcomeRoute: typeof OnboardingLayoutWelcomeRoute
}

const OnboardingLayoutRouteChildren: OnboardingLayoutRouteChildren = {
  OnboardingLayoutAgentKeyRoute: OnboardingLayoutAgentKeyRoute,
  OnboardingLayoutCompleteRoute: OnboardingLayoutCompleteRoute,
  OnboardingLayoutGithubAppRoute: OnboardingLayoutGithubAppRoute,
  OnboardingLayoutGithubRepoRoute: OnboardingLayoutGithubRepoRoute,
  OnboardingLayoutModeSelectRoute: OnboardingLayoutModeSelectRoute,
  OnboardingLayoutWelcomeRoute: OnboardingLayoutWelcomeRoute,
}

const OnboardingLayoutRouteWithChildren =
  OnboardingLayoutRoute._addFileChildren(OnboardingLayoutRouteChildren)

interface OnboardingRouteChildren {
  OnboardingLayoutRoute: typeof OnboardingLayoutRouteWithChildren
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingLayoutRoute: OnboardingLayoutRouteWithChildren,
  OnboardingIndexRoute: OnboardingIndexRoute,
}

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(
  OnboardingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  DnsRoute: DnsRoute,
  DocsRoute: DocsRoute,
  FeaturesRoute: FeaturesRoute,
  GetStartedRoute: GetStartedRoute,
  GithubRoute: GithubRoute,
  LogoExperimentRoute: LogoExperimentRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  GithubappCallbackRoute: GithubappCallbackRoute,
  GithubappSuccessRoute: GithubappSuccessRoute,
  OauthConsentRoute: OauthConsentRoute,
  OnboardingRoute: OnboardingRouteWithChildren,
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
  ServicesServiceIdRoute: ServicesServiceIdRoute,
  SettingsAccessRoute: SettingsAccessRoute,
  SettingsApiKeysRoute: SettingsApiKeysRoute,
  SettingsDnsRoute: SettingsDnsRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
